### ISSUE TITLE
Update gems to latest versions

### ISSUE THREAD

**Issue by steveyken** [crossroads/api.goodcity#1322]
Where safe, update gems to more recent versions

**Comment by steveyken** [comment]
@abulsayyad123 @swatijadhav @namrataukirde any interest for some Hacktoberfest PRs? :)

**Comment by namrataukirde** [comment]
Yes 👍

**Comment by steveyken** [comment]
thank you!

**Comment by namrataukirde** [comment]
@steveyken Is this still valid? Can I contribute in anything as part of hactoberfest ?

**Comment by steveyken** [comment]
yes this would be very helpful, thank you

**Comment by steveyken** [comment]
I've been doing this
